name: Example Deploy Application into Docker Swarm
on:
  push:
    branches:
      - "dev"
    paths:
      - .github/workflows/example_deploy_docker.yaml
      - docker-stack.yaml

permissions:
  id-token: write
  contents: read
jobs:
  deploy:  
    name: Example Deploy Application into docker swarm
    runs-on: master
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy application images to Docker Swarm
        run: |
          docker node ls
          docker service ls
          docker stack ls
          docker stack rm stackdemo
          sleep 30
          docker stack deploy --compose-file docker-stack.yml stackdemo